@startuml
:Usuario: as usr
:Administrador: as admin
admin <|---- usr

usr -->(Cadastrar)
usr -->(logar)
usr --> (Atualizar informacao)
usr --> (Publicar)
usr --> (adicionar eventos)
usr -->(Gerir conta)
usr -->(Manter amigo)
usr -->(Configurar conversa)
usr --> (solicitar amizade)
usr -->(Gerenciar Conversa)
usr -->(adicionar favoritos)
admin -->(Criar grupo)
admin -->(Manter membro)
admin -->(Gerenciar grupo)

@enduml
